services:
    database:
        image: "postgres:16.6-alpine3.20"
        container_name: "postgres-dev"
        env_file:
            - "../.env.development"
        ports:
            - "8080:5432"
